package com.tlw.jdbctemplate.snippets;

import com.alibaba.fastjson.JSON;
import com.tlw.jdbctemplate.snippets.ch01_sample.User;
import org.junit.Before;
import org.junit.Test;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

/**
 * Created by hdp on 2017/6/18.
 */
public class C01QueryMix {

    Context context = new Context();

    @Before
    public void create() {
        context.getJDBC_Template().execute("create table user (id int AUTO_INCREMENT primary key, userName varchar(32), password varchar(32))");
        context.getJDBC_Template().execute("insert into user (userName, password) values ('xxx', 'zzz')");
        context.getJDBC_Template().execute("insert into user (userName, password) values ('xxx', 'zzz')");
    }

    @Test
    public void queryCount() {
        int count = context.getJDBC_Template().queryForObject("select count(*) from user", Integer.class);
        System.out.println(count);
    }

    @Test
    public void queryCountByParam() {
        int count = context.getJDBC_Template().queryForObject("select count(*) from user where userName = ?", new Object[]{"user1"}, Integer.class);
        System.out.println(count);
    }

    @Test
    public void queryString() {
        String name = context.getJDBC_Template().queryForObject("select userName from user where id = 1", String.class);
        System.out.println(name);
    }

    @Test
    public void queryObject() {
        User user = context.getJDBC_Template().queryForObject("select * from user where id = 1", (rs, rowNum) -> {
            User user1 = new User();
            user1.setId(rs.getInt("id"));
            user1.setUserName(rs.getString("userName"));
            user1.setPassword(rs.getString("password"));
            return user1;
        });
        System.out.println(user);
    }

    @Test
    public void testQueryForObject2() {
        String name = context.getJDBC_Template().queryForObject("select userName from user where id = 1", String.class);
        System.out.println(name);
    }

    @Test
    public void testQueryForList() {
        List<String> names = context.getJDBC_Template().queryForList("select userName from user", String.class);
        names.forEach(name -> System.out.println(name));
    }

    @Test
    public void testQueryForList1() {
        List<Map<String, Object>> users = context.getJDBC_Template().queryForList("select * from user");
        System.out.println(JSON.toJSONString(users));
    }

    @Test
    public void testUpdate() {
        context.getJDBC_Template().update("update user set userName=? where id = ?", "user2", 2);
    }

    @Test
    public void retrievingAutoGeneratedKeys() {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        context.getJDBC_Template().update(con -> {
            PreparedStatement ps = con.prepareCall("insert into user (userName) values (?)");
            ps.setString(1, "user4");
            return ps;
        }, keyHolder);
        System.out.println(keyHolder.getKey());
    }
}
